import { WorkoutPlan } from '../types';

declare global {
  interface Window {
    jspdf: any;
  }
}

export const generateWorkoutPDF = (plan: WorkoutPlan) => {
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF();
  
  // Header
  doc.setFillColor(30, 41, 59); // Dark slate
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(163, 230, 53); // Lime color
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("HYBRID ONE COACH", 105, 20, { align: "center" });
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(`Plan: ${plan.title || 'Workout Plan'}`, 105, 30, { align: "center" });

  let yPos = 50;

  if (plan.sessions && Array.isArray(plan.sessions)) {
    plan.sessions.forEach((session, index) => {
        // Check for page break
        if (yPos > 250) {
        doc.addPage();
        yPos = 20;
        }

        // Session Header
        doc.setFillColor(240, 240, 240);
        doc.rect(10, yPos - 6, 190, 8, 'F');
        doc.setTextColor(0, 0, 0);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(11);
        doc.text(`${session.day}: ${session.focus}`, 12, yPos);
        yPos += 10;

        // Content Style
        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        
        // Warmup
        if (session.warmup && Array.isArray(session.warmup) && session.warmup.length > 0) {
        doc.setTextColor(100, 100, 100);
        doc.text("Warmup:", 15, yPos);
        doc.setTextColor(0, 0, 0);
        session.warmup.forEach(line => {
            doc.text(`• ${line}`, 35, yPos);
            yPos += 5;
        });
        yPos += 2;
        }

        // Main Work
        if (session.mainWork && Array.isArray(session.mainWork) && session.mainWork.length > 0) {
        doc.setTextColor(30, 41, 59);
        doc.setFont("helvetica", "bold");
        doc.text("Main Work:", 15, yPos);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(0, 0, 0);
        session.mainWork.forEach(line => {
            const splitText = doc.splitTextToSize(`• ${line}`, 150);
            doc.text(splitText, 35, yPos);
            yPos += (5 * splitText.length);
        });
        yPos += 2;
        }
        
        // Notes
        if (session.notes) {
        doc.setTextColor(100, 100, 100);
        doc.setFontSize(9);
        const noteText = doc.splitTextToSize(`Note: ${session.notes}`, 170);
        doc.text(noteText, 15, yPos);
        yPos += (5 * noteText.length);
        doc.setFontSize(10);
        }

        yPos += 10; // Spacing between days
    });
  }

  doc.save(`${(plan.title || 'Plan').replace(/\s+/g, '_')}_Schedule.pdf`);
};

export const generateAnalysisPDF = (plan: WorkoutPlan) => {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();
    
    // Header
    doc.setFillColor(15, 23, 42); // Even darker slate
    doc.rect(0, 0, 210, 40, 'F');
    
    doc.setTextColor(163, 230, 53); // Lime color
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("PROGRAM ANALYSIS", 105, 20, { align: "center" });
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.text(`Scientific Breakdown for: ${plan.title || 'Workout Plan'}`, 105, 30, { align: "center" });
  
    let yPos = 55;
    const margin = 20;
    const pageWidth = 170; // 210 - 20 - 20
  
    // Title
    doc.setTextColor(0, 0, 0);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text("Methodology & Scientific Rationale", margin, yPos);
    yPos += 10;
  
    // Content
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(40, 40, 40);

    const analysisText = plan.analysis || "No detailed analysis provided for this plan.";
    
    // Split text to fit page width
    const splitText = doc.splitTextToSize(analysisText, pageWidth);
    
    // Iterate and add pages if needed
    splitText.forEach((line: string) => {
        if (yPos > 270) {
            doc.addPage();
            yPos = 20;
        }
        doc.text(line, margin, yPos);
        yPos += 6;
    });

    // Add footer disclaimer
    if (yPos > 260) {
        doc.addPage();
        yPos = 20;
    }
    yPos += 10;
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by HybridOne Coach AI. Educational purposes only.", margin, yPos);
  
    doc.save(`${(plan.title || 'Plan').replace(/\s+/g, '_')}_Analysis.pdf`);
  };